# Generated by Django 5.1 on 2024-09-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionDePeaje',
            fields=[
                ('numero_de_estacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTarifas',
            fields=[
                ('id_historial', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tarifa', models.FloatField()),
                ('tarifa_actual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NoPagados',
            fields=[
                ('id_no_pagado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_conductor', models.CharField(max_length=255)),
                ('apellido_conductor', models.CharField(max_length=255)),
                ('dni_conductor', models.CharField(max_length=20)),
                ('fecha_hora_de_emision', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id_operador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id_tipo_vehiculo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CasillaDePeaje',
            fields=[
                ('numero_de_casilla', models.IntegerField(primary_key=True, serialize=False)),
                ('sentido_de_cobro', models.CharField(max_length=255)),
                ('numero_de_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.estaciondepeaje')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEfectivo',
            fields=[
                ('id_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora_de_emision', models.DateTimeField()),
                ('importe_cobrado', models.FloatField()),
                ('codigo_QR', models.CharField(blank=True, max_length=255, null=True)),
                ('id_historial_tarifas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.historialtarifas')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTelepase',
            fields=[
                ('id_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora_de_emision', models.DateTimeField()),
                ('importe_cobrado', models.FloatField()),
                ('codigo_telepase', models.CharField(default='SIN_CODIGO', max_length=255)),
                ('usuario', models.CharField(default='No especificado', max_length=255)),
                ('direccion', models.CharField(default='No especificado', max_length=255)),
                ('patente', models.CharField(default='SIN_PATENTE', max_length=255)),
                ('tarjeta_debito', models.IntegerField(default='SIN_DATOS')),
                ('id_historial_tarifas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.historialtarifas')),
            ],
        ),
        migrations.CreateModel(
            name='Pasada',
            fields=[
                ('id_pasada', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora_de_pasada', models.DateTimeField()),
                ('pasada_telepase', models.CharField(blank=True, max_length=255, null=True)),
                ('pasada_efectivo', models.CharField(blank=True, max_length=255, null=True)),
                ('pasada_no_paga', models.CharField(blank=True, max_length=255, null=True)),
                ('id_tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.tipovehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='historialtarifas',
            name='id_tipo_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.tipovehiculo'),
        ),
        migrations.CreateModel(
            name='TurnoDeTrabajo',
            fields=[
                ('id_turno', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora_de_inicio', models.DateTimeField()),
                ('fecha_hora_de_fin', models.DateTimeField()),
                ('monto_de_cambio_entregado', models.FloatField()),
                ('plata_inicial', models.FloatField()),
                ('plata_final', models.FloatField()),
                ('id_operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.operador')),
                ('numero_de_casilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.casilladepeaje')),
                ('numero_de_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.estaciondepeaje')),
            ],
        ),
    ]
