# Generated by Django 5.1 on 2024-10-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peaje_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nopagados',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nopagados',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
