# Generated by Django 5.1.2 on 2024-10-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peaje_App', '0002_nopagados_importe_nopagados_tipo_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='dni',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
