# Generated by Django 5.1 on 2024-10-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peaje_App', '0003_operador_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='contraseña',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
