# Generated by Django 5.1 on 2024-10-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peaje_App', '0004_operador_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='contraseña',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
