# Generated by Django 5.1 on 2024-10-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peaje_App', '0008_alter_operador_id_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='id_operador',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
