# Generated by Django 5.1.1 on 2024-10-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Peaje_App', '0010_alter_operador_id_operador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnodetrabajo',
            name='plata_final',
        ),
    ]
