# Generated by Django 5.1.1 on 2024-10-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peaje_App', '0011_remove_turnodetrabajo_plata_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnodetrabajo',
            name='monto_de_cambio_entregado',
        ),
        migrations.RemoveField(
            model_name='turnodetrabajo',
            name='plata_inicial',
        ),
        migrations.AddField(
            model_name='turnodetrabajo',
            name='sentido_de_cobro',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, null=True),
        ),
    ]
