# Generated by Django 4.2.16 on 2024-10-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Peaje_App', '0012_remove_turnodetrabajo_monto_de_cambio_entregado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnodetrabajo',
            name='sentido_de_cobro',
        ),
    ]
